print("<>----<> TEMA 3 <>----<>")
print("+" + 13 * "-" + "+")
print(("|" + " Ejercicio 2 "+ "|\n"), end="")
print("+" + 13 * "-" + "+")

peso: int =int(input("Escribe tu peso en kg: "))
estatura: float =float(input("Escribe tu estatura: "))
print("Calculamos peso / altura ^ 2 y usamos round con 2 decimales")
imc= round (peso / estatura ** 2, 2 )
print("El índice de masa corporal calculado es: "+ str(imc))
